version: '3.8'

services:
  marqo:
    image: marqoai/marqo:latest
    ports:
      - "8882:8882"
    environment:
      - MARQO_ENABLE_BATCH_APIS=True
    volumes:
      - marqo_data:/opt/vespa/var

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MARQO_URL=http://marqo:8882
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./api/uploads:/app/uploads
      - ./archive/docs-sm:/app/archive/docs-sm
    depends_on:
      - marqo
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./api
          target: /app
          ignore:
            - "__pycache__/"
            - "*.pyc"
        - action: rebuild
          path: ./api/requirements.txt

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000/api/v1
    depends_on:
      - api
    restart: unless-stopped

volumes:
  marqo_data:
